# Based on https://jekyllrb.com/docs/continuous-integration/

language: ruby

rvm:
- 2.1

install: bundle install

script: 
- jekyll build

# There are errors right now: https://github.com/Caleydo/caleydo.github.io/issues/83
#
# - htmlproofer ./_site --disable-external
# env:
#   global:
#   - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
