# Based on https://jekyllrb.com/docs/continuous-integration/

language: ruby

rvm:
- 2.1

install: bundle install

script: 
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --disable-external  --alt-ignore '/.*/' --url-swap '/assets/images/papers/$:/assets/images/papers/2016_eurovis_pathfinder_teaser.png'
# JS add the last part of the URL, which is missing in the static file
- bash .build-tools/cron_job.sh

- ruby -run -e httpd . -p 5000 # Jekyll seems like overkill here, but might be making the wrong call.
- phantomjs run-qunit.js http://localhost:5000/_documentation/tutorial/web_bundle/qunit.html?0

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
