# Based on https://jekyllrb.com/docs/continuous-integration/

language: ruby
cache: bundler

rvm:
- 2.2.2

install:
- bundle install

script: 
- set -e
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --disable-external  --alt-ignore '/.*/' --url-swap '/assets/images/papers/$:/assets/images/papers/2016_eurovis_pathfinder_teaser.png'

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
